// data.js
export const caseTypes = [
  { value: "AAP", label: "ARB.A." },
  { value: "ARBACOMM", label: "ARB. A. (COMM.)" },
  { value: "AA", label: "ARB.P." },
  { value: "BA", label: "BAIL APPLN." },
  { value: "CAA", label: "CA" },
  { value: "CACR", label: "CA (COMM.IPD-CR)" },
  { value: "CAG", label: "C.A.(COMM.IPD-GI)" },
  { value: "CAP", label: "C.A.(COMM.IPD-PAT)" },
  { value: "CAPP", label: "C.A.(COMM.IPD-PV)" },
  { value: "CAT", label: "C.A.(COMM.IPD-TM)" },
  { value: "CAVC", label: "CAVEAT(CO.)" },
  { value: "CC", label: "CC" },
  { value: "CCCOMM", label: "CC(COMM)" },
  { value: "CCPCO", label: "CCP(CO.)" },
  { value: "CCPO", label: "CCP(O)" },
  { value: "CCPRF", label: "CCP(REF)" },
  { value: "CEAC", label: "CEAC" },
  { value: "CEAR", label: "CEAR" },
  { value: "CHATAC", label: "CHAT.A.C." },
  { value: "CHATRF", label: "CHAT.A.REF" },
  { value: "CMA", label: "CM APPL." },
  { value: "CMI", label: "CMI" },
  { value: "CMM", label: "CM(M)" },
  { value: "CMMI", label: "CM(M)-IPD" },
  { value: "CO", label: "C.O." },
  { value: "COA", label: "CO.APP." },
  { value: "CA", label: "CO.APPL." },
  { value: "CAC", label: "CO.APPL.(C)" },
  { value: "CAM", label: "CO.APPL.(M)" },
  { value: "COASB", label: "CO.A(SB)" },
  { value: "COC", label: "C.O.(COMM.IPD-CR)" },
  { value: "COG", label: "C.O.(COMM.IPD-GI)" },
  { value: "COP", label: "C.O.(COMM.IPD-PAT)" },
  { value: "COT", label: "C.O. (COMM.IPD-TM)" },
  { value: "COEX", label: "CO.EX." },
  { value: "CCA", label: "CONT.APP.(C)" },
  { value: "CCP", label: "CONT.CAS(C)" },
  { value: "CRLCC", label: "CONT.CAS.(CRL)" },
  { value: "CP", label: "CO.PET." },
  { value: "COSECR", label: "CO.SEC.REF" },
  { value: "CRLA", label: "CRL.A." },
  { value: "CRLCRF", label: "CRL.C.REF." },
  { value: "CRLMP", label: "CRL.L.P." },
  { value: "CRLMA", label: "CRL.M.A." },
  { value: "CRLMB", label: "CRL.M.(BAIL)" },
  { value: "CRLMM", label: "CRL.M.C." },
  { value: "CRLMC", label: "CRL.M.(CO.)" },
  { value: "CRLMI", label: "CRL.M.I." },
  { value: "CRLO", label: "CRL.O." },
  { value: "CRLOC", label: "CRL.O.(CO.)" },
  { value: "CRLRF", label: "CRL.REF." },
  { value: "CRLR", label: "CRL.REV.P." },
  { value: "CRLRMAT", label: "CRL.REV.P.(MAT.)" },
  { value: "CRLRNDPS", label: "CRL.REV.P.(NDPS)" },
  { value: "CRLRNI", label: "CRL.REV.P.(NI)" },
  { value: "CR", label: "C.R.P." },
  { value: "CRI", label: "CRP-IPD" },
  { value: "CRULE", label: "C.RULE" },
  { value: "SC", label: "CS(COMM)" },
  { value: "SCI", label: "CS(COMM) INFRA" },
  { value: "S", label: "CS(OS)" },
  { value: "CUSAA", label: "CUSAA" },
  { value: "CUSAC", label: "CUS.A.C." },
  { value: "CUSAR", label: "CUS.A.R." },
  { value: "CUSTOMA", label: "CUSTOM A." },
  { value: "DSRF", label: "DEATH SENTENCE REF." },
  { value: "EDC", label: "EDC" },
  { value: "EDR", label: "EDR" },
  { value: "EFAC", label: "EFA(COMM)" },
  { value: "EFAOS", label: "EFA(OS)" },
  { value: "EFAOSCOMM", label: "EFA(OS)  (COMM)" },
  { value: "EFI", label: "EFA(OS)(IPD)" },
  { value: "EP", label: "EL.PET." },
  { value: "ETR", label: "ETR" },
  { value: "EA", label: "EX.APPL.(OS)" },
  { value: "EFA", label: "EX.F.A." },
  { value: "EX", label: "EX.P." },
  { value: "ESA", label: "EX.S.A." },
  { value: "FAO", label: "FAO" },
  { value: "FAOC", label: "FAO (COMM)" },
  { value: "FAI", label: "FAO-IPD" },
  { value: "FAOOS", label: "FAO(OS)" },
  { value: "FAC", label: "FAO(OS) (COMM)" },
  { value: "FAOI", label: "FAO(OS)(IPD)" },
  { value: "GCAC", label: "GCAC" },
  { value: "GCAR", label: "GCAR" },
  { value: "GTA", label: "GTA" },
  { value: "GTC", label: "GTC" },
  { value: "GTR", label: "GTR" },
  { value: "IA", label: "I.A." },
  { value: "IPA", label: "I.P.A." },
  { value: "ITA", label: "ITA" },
  { value: "ITC", label: "ITC" },
  { value: "ITR", label: "ITR" },
  { value: "ITSA", label: "ITSA" },
  { value: "LAA", label: "LA.APP." },
  { value: "LPA", label: "LPA" },
  { value: "MACA", label: "MAC.APP." },
  { value: "MAT", label: "MAT." },
  { value: "MATA", label: "MAT.APP." },
  { value: "MATFC", label: "MAT.APP.(F.C.)" },
  { value: "MATC", label: "MAT.CASE" },
  { value: "MATRF", label: "MAT.REF." },
  { value: "PMLA", label: "MISC. APPEAL(PMLA)" },
  { value: "OAA", label: "O.A." },
  { value: "OA", label: "OA" },
  { value: "OCJA", label: "OCJA" },
  { value: "OMP", label: "O.M.P." },
  { value: "OMPCOMM", label: "O.M.P. (COMM)" },
  { value: "OMP(CONT.)", label: "OMP (CONT.)" },
  { value: "OE", label: "O.M.P. (E)" },
  { value: "OMPECOMM", label: "O.M.P. (E) (COMM.)" },
  { value: "OMPEFACOMM", label: "O.M.P.(EFA)(COMM.)" },
  { value: "OF", label: "O.M.P. (ENF.)" },
  { value: "OMPENFCOMM", label: "OMP (ENF.) (COMM.)" },
  { value: "OI", label: "O.M.P.(I)" },
  { value: "OMPICOMM", label: "O.M.P.(I) (COMM.)" },
  { value: "OMPMISC", label: "O.M.P. (MISC.)" },
  { value: "OMPMISCCOMM", label: "O.M.P.(MISC.)(COMM.)" },
  { value: "OMPT", label: "O.M.P.(T)" },
  { value: "OMPTCOMM", label: "O.M.P. (T) (COMM.)" },
  { value: "OREF", label: "O.REF." },
  { value: "RCR", label: "RC.REV." },
  { value: "RCSA", label: "RC.S.A." },
  { value: "RERA", label: "RERA APPEAL" },
  { value: "REVIEWPET", label: "REVIEW PET." },
  { value: "RFA", label: "RFA" },
  { value: "RFAC", label: "RFA(COMM)" },
  { value: "RFI", label: "RFA-IPD" },
  { value: "RFAOS", label: "RFA(OS)" },
  { value: "RFC", label: "RFA(OS)(COMM)" },
  { value: "RFO", label: "RFA(OS)(IPD)" },
  { value: "RSA", label: "RSA" },
  { value: "SCA", label: "SCA" },
  { value: "SDR", label: "SDR" },
  { value: "SERTA", label: "SERTA" },
  { value: "STA", label: "ST.APPL." },
  { value: "STR", label: "ST.REF." },
  { value: "SRTRF", label: "SUR.T.REF." },
  { value: "PR", label: "TEST.CAS." },
  { value: "TRPC", label: "TR.P.(C)" },
  { value: "TPC", label: "TR.P.(C.)" },
  { value: "TRP", label: "TR.P.(CRL.)" },
  { value: "VATA", label: "VAT APPEAL" },
  { value: "CW", label: "W.P.(C)" },
  { value: "WO", label: "W.P.(C)-IPD" },
  { value: "WC", label: "WP(C)(IPD)" },
  { value: "CRLW", label: "W.P.(CRL)" },
  { value: "WTA", label: "WTA" },
  { value: "WTC", label: "WTC" },
  { value: "WTR", label: "WTR" },
];
